name: Build the Viewer

on:
  push:                  # Triggered on push events
    branches: [ main ]   # Specify the branches to trigger on

jobs:
  build:
    runs-on: windows-2019   # Specify the environment to run on
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Check out the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up Python
        with:
          python-version: '3.9'  # Specify the Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Build Executable
        run: |
          pyinstaller --onefile --windowed viewer.py  # Build the executable
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: viewer-executable  # Name of the artifact
          path: dist/viewer.exe     # Path to the built executable
