name: Build the viewer

on:
  commit:
    branches: [ master ]


jobs:
  build:
    runs-on: [windows-2019]
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install -r requirements.txt
          pyinstaller --onefile --windowed viewer.py
 